# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20170727_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
