# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20170727_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='alumni',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumni',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='cv_url',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='cv_url',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
