# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_school_skill_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept_stud',
            new_name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='I live in Kolkata'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_curr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
