# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20170729_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='projects_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='publications',
            field=models.TextField(),
        ),
    ]
