# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20170729_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='works_at',
            new_name='position',
        ),
    ]
