# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_auto_20170729_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='school_studied',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_studied',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
