# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 21:42
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_auto_20170729_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='image_std',
            field=stdimage.models.StdImageField(default='', upload_to=stdimage.utils.UploadToUUID(path='images')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image_std',
            field=stdimage.models.StdImageField(default='', upload_to=stdimage.utils.UploadToUUID(path='images')),
            preserve_default=False,
        ),
    ]
