# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_auto_20170730_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
