# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=15)),
                ('bio', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=1000)),
                ('cv_url', models.CharField(max_length=1000)),
                ('works_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='course_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_roll', models.IntegerField(max_length=15)),
                ('email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=15)),
                ('bio', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=1000)),
                ('cv_url', models.CharField(max_length=1000)),
                ('year_of_study', models.IntegerField(max_length=1)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.course_in')),
                ('dept_stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.departments')),
                ('work_field_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.interests')),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='dept_alum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.departments'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='work_field_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.interests'),
        ),
    ]
