# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20170727_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username_roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(),
        ),
    ]
