# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20170729_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='projects_info',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='publications',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school_studied',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Users.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, to='Users.Skill'),
        ),
        migrations.AddField(
            model_name='student',
            name='univ_studying',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Users.University'),
            preserve_default=False,
        ),
    ]
