# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20170729_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='skills',
            field=models.ManyToManyField(blank=True, to='Users.Skill'),
        ),
    ]
